spring:
  datasource:
    name: atmapp
    url: jdbc:mysql://localhost:3306/atmapp
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8181